version: "3"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi.hole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    env_file: ./.env
    environment:
      TZ: 'Europe/Berlin'
      PIHOLE_DNS_: 208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53 # OpenDNS
      WEBTHEME: default-darker
    volumes:
      - './.docker/etc-pihole:/etc/pihole'
      - './.docker/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
